apiVersion: v1
kind: Service
metadata:
  name: {{ include "ckodex-kserve-llm-operator.fullname" . }}
  labels:
    {{- include "ckodex-kserve-llm-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: metrics
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: health
  selector:
    {{- include "ckodex-kserve-llm-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
