{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ckodex-kserve-llm-operator.fullname" . }}
  labels:
    {{- include "ckodex-kserve-llm-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ckodex-kserve-llm-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
