apiVersion: v2
name: ckodex-kserve-llm-operator
description: A production-grade Kubernetes operator for managing distributed LLM inference workloads.
type: application
version: 0.18.0-beta.6
appVersion: "v0.18.0-beta.6"
keywords:
  - kubernetes
  - llm
  - machine-learning
  - vllm
  - gemma4
  - serving
home: https://github.com/ckodex-labs/ckodex-kserve-llm
sources:
  - https://github.com/ckodex-labs/ckodex-kserve-llm
maintainers:
  - name: CKodex Labs
    email: maintainers@ckodex.org
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/ckodex-labs/ckodex-kserve-llm/tree/main/docs
