{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ckodex-kserve-llm-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ckodex-kserve-llm-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: metrics
      port: 8091
      targetPort: 8091
      protocol: TCP
{{- end }}
