apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-vllm
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: vllm
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65532
            capabilities:
              drop:
                - ALL
