apiVersion: serving.ckodex.com/v1alpha2
kind: LLMInferenceService
metadata:
  name: llama3-8b-test
  namespace: ckodex-inference
spec:
  model:
    uri: hf://openai-community/gpt2
    name: gpt2
  replicas: 1
  template:
    spec:
      containers:
      - name: vllm
        image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.17.1
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        ports:
        - containerPort: 8000
  router:
    gateway:
      managed:
        gatewayClassName: envoy
    route:
      httpRoute:
        hostnames:
        - llama3-test.local
    scheduler:
      pool:
        selector:
          app.kubernetes.io/instance: llama3-8b-test
  scaling:
    minReplicas: 1
