apiVersion: serving.ckodex.com/v1
kind: LLMInferenceService
metadata:
  name: gemma-4-26b-a4b
  namespace: ckodex-inference
spec:
  model:
    uri: hf://google/gemma-4-26B-A4B-it
    name: google/gemma-4-26B-A4B-it
  replicas: 1
  parallelism:
    expert: true
  template:
    spec:
      containers:
      - name: vllm
        resources:
          limits:
            cpu: "32"
            memory: 128Gi
            nvidia.com/gpu: "1"
  router:
    gateway:
      managed:
        gatewayClassName: envoy
    route:
      httpRoute: {}
    scheduler:
      pool: {}
