apiVersion: serving.ckodex.com/v1
kind: LLMInferenceService
metadata:
  name: gemma-4-2b
  namespace: ckodex-inference
spec:
  model:
    uri: hf://google/gemma-4-E2B-it
    name: google/gemma-4-E2B-it
  replicas: 1
  template:
    spec:
      containers:
      - name: vllm
        resources:
          limits:
            cpu: "8"
            memory: 32Gi
            nvidia.com/gpu: "1"
  router:
    gateway:
      managed:
        gatewayClassName: envoy
    route:
      httpRoute: {}
    scheduler:
      pool: {}
