apiVersion: serving.ckodex.com/v1alpha2
kind: LLMInferenceService
metadata:
  name: gemma-4-31b
  namespace: ckodex-inference
spec:
  model:
    uri: hf://google/gemma-4-31B-it
    name: google/gemma-4-31B-it
  replicas: 1
  # The operator will apply TP=2 and 2 GPUs for this 33B dense model.
  router:
    gateway:
      managed:
        gatewayClassName: envoy
    route:
      httpRoute: {}
    scheduler:
      pool: {}
