apiVersion: serving.ckodex.com/v1
kind: LLMInferenceService
metadata:
  name: gemma-4-31b
  namespace: ckodex-inference
spec:
  model:
    uri: hf://google/gemma-4-31B-it
    name: google/gemma-4-31B-it
  replicas: 1
  parallelism:
    tensor: 2
  template:
    spec:
      containers:
      - name: vllm
        resources:
          limits:
            cpu: "32"
            memory: 256Gi
            nvidia.com/gpu: "2"
  router:
    gateway:
      managed:
        gatewayClassName: envoy
    route:
      httpRoute: {}
    scheduler:
      pool: {}
